services:
  influxdb:
    image: influxdb:2.7.11
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  grafana:
    build: 
      context: ./grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ../Models:/etc/grafana/models
      - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting:ro
    depends_on:
      - influxdb
      - blackbox-exporter
      - prometheus
      - grafana-image-renderer
    ports:
      - ${GRAFANA_PORT}:3000
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      python3 /etc/grafana/provisioning/dashboards/modify_dashboard.py &&
      /run.sh"
    environment:
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=Grafana
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_RENDERING_CONCURRENT_RENDER_LIMIT=5

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "${BLACKBOX_PORT}:9115"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/targets:/etc/prometheus/targets:ro
    ports:
      - "${PROMETHEUS_PORT}:9090"
    depends_on:
      - blackbox-exporter

  grafana-image-renderer:
    image: grafana/grafana-image-renderer:3.0.0
    ports:
      - "8081:8081"
    restart: unless-stopped
    # depends_on:
    #   - grafana

volumes:
  grafana-storage:
  influxdb-storage:
