apiVersion: 1

groups:
  - orgId: 1
    name: "WD Evaluation group"
    folder: "WD Folder rule"
    interval: 1m
    rules:
      - uid: apiAlertDown
        title: "API Alert down"
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus_uid
            model:
              datasource:
                type: prometheus
                uid: prometheus_uid
              editorMode: code
              expr: probe_success
              hide: false
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                      - 0
                    type: lt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: A
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: KeepLast
        execErrState: Error
        for: 1m
        annotations:
          summary: "🚨 API Alert: Service Down on {{ .Labels.instance }}"
          description: "API service on {{ .Labels.instance }} is unresponsive! Immediate action required. Notified by Watchdog Middleware 🐶"
        isPaused: ${GF_NOTIFIER_EMAIL_DISABLE}
        labels:
            contact: "whatchdog_email"
