apiVersion: 1

contactPoints:
  - orgId: 1
    name: whatchdog_email
    uid: whatchdog_email_uid
    receivers:
      - uid: email_receiver
        type: email
        settings:
          addresses: ${ALERT_EMAILS}

policies:
  - orgId: 1
    receiver: whatchdog_email
    group_by: ['...']
    routes:
      - receiver: whatchdog_email
        match:
          contact: whatchdog_email