{
 "title": "Watchdog Middleware",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": { "query": "SHOW DATABASES" } },
   {
    "name": "dataTable",
    "label": "DataTable",
    "query": {
     "query": "SHOW MEASUREMENTS ON \"$bucket\" WHERE \"req_api\" != ''"
    }
   },
   {
    "name": "ckptDataTable",
    "label": "Checkpoint DataTable",
    "query": {
     "query": "SHOW MEASUREMENTS ON \"$bucket\" WHERE \"ckpt_api\" != ''"
    }
   },
   {
    "name": "api",
    "label": "API",
    "query": {
     "query": "SHOW TAG VALUES FROM /^(?:${dataTable:regex}|${ckptDataTable:regex})$/ WITH KEY IN (\"req_api\", \"ckpt_api\")"
    }
   },
   {
    "name": "apiStatus",
    "label": "API Status",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   },
   { "name": "detailsQuery" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\r\n    display: flex;\r\n    justify-content: space-between;\r\n    align-items: center;\r\n    background: linear-gradient(135deg, #9B68A7 0%, #7A4A7C 100%);\r\n    border: 4px solid rgba(255, 255, 255, 0.1);\r\n    border-radius: 25px;\r\n    padding: 30px 50px;\r\n    font-family: Arial, sans-serif;\r\n    color: #ffffff;\r\n    max-width: 100%;\r\n    margin: 30px auto;\r\n    box-shadow: \r\n        0 10px 20px rgba(0, 0, 0, 0.2),\r\n        inset 0 2px 10px rgba(255, 255, 255, 0.1);\r\n\">\r\n    <div style=\"flex-grow: 1;\">\r\n        <h1 style=\"\r\n            font-size: 4.2em;\r\n            margin: 10px 0;\r\n            font-weight: 800;\r\n            letter-spacing: -1px;\r\n            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);\r\n        \">Watchdog Middleware <span style=\"font-size: 0.9em;\">🐶</span></h1>\r\n    </div>\r\n    <div style=\"\r\n        display: flex;\r\n        flex-direction: column;\r\n        align-items: flex-start;\r\n        margin-left: 40px;\r\n    \">\r\n        <p style=\"font-size: 1.3em; margin: 5px 0; font-weight: bold;\">By Rubén Martínez</p>\r\n        <a href=\"https://github.com/RubenMartinezSiso\" \r\n           target=\"_blank\" \r\n           style=\"text-decoration: none; display: inline-flex; align-items: center; background-color: #9B68A7; color: #ffffff; padding: 8px 20px; border-radius: 10px; font-weight: bold; font-size: 1.2em; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\">\r\n            <span style=\"margin-right: 8px;\">🚀</span> Visit my GitHub\r\n        </a>\r\n    </div>\r\n</div>\r\n"
   }
  },
  {
   "title": "🚀 API Status Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
     "options": {
      "content": "<div style=\"text-align: left; width: 100%;\">\r\n    <hr style=\"border: 1px solid white; margin-top: 5px; margin-bottom: 10px;\">\r\n    <h2 style=\"font-weight: bold; font-size: 1.8em; margin-top: 0; margin-bottom: 5px;\">Status</h2>\r\n</div>\r\n"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 20, "x": 4, "y": 7 },
     "options": {
      "content": "<div style=\"text-align: left; width: 100%;\">\r\n    <hr style=\"border: 1px solid white; margin-top: 5px; margin-bottom: 10px;\">\r\n    <h2 style=\"font-weight: bold; font-size: 1.8em; margin-top: 0; margin-bottom: 5px;\">Response Time</h2>\r\n</div>\r\n"
     }
    },
    {
     "title": "🌐 $apiStatus",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 51 },
     "repeat": "apiStatus",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{instance=\"$apiStatus\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🌐 $apiStatus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 51 },
     "repeat": "apiStatus",
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=\"$apiStatus\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "📥 Last Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
     "options": {
      "content": "<div style=\"text-align: left; width: 100%;\">\r\n    <hr style=\"border: 1px solid white; margin-top: 5px; margin-bottom: 10px;\">\r\n    <h2 style=\"font-weight: bold; font-size: 1.8em; margin-top: 0; margin-bottom: 5px;\">Last Requests</h2>\r\n</div>\r\n"
     }
    },
    {
     "title": "Requests",
     "type": "table",
     "gridPos": { "h": 14, "w": 16, "x": 0, "y": 10 },
     "targets": [
      {
       "query": "SELECT\n    time,\n    req_timestamp AS \"Hiden Timestamp\", \n    req_timestamp AS \"Show details\", \n    req_api AS \"API\", \n    req_path AS \"Path\", \n    req_method AS \"Method\", \n    req_route_controller AS \"Controller\", \n    req_route_action AS \"Action\", \n    res_status_code AS \"Status\"\nFROM /^(?:$dataTable)$/\nWHERE $timeFilter AND req_api =~ /^($api)$/\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "Request Details",
     "type": "table",
     "description": "Click on 'Show details' in the table on the left to explore the data.",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "query": "data = from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${dataTable:regex}/)\n  |> filter(fn: (r) => contains(value: r.req_api, set: ${api:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"req_timestamp\"\n        or r[\"_field\"] == \"req_query_string\"\n        or r[\"_field\"] == \"req_body\"\n        or r[\"_field\"] == \"req_host\"\n        or r[\"_field\"] == \"req_client_ip\"\n        or r[\"_field\"] == \"req_location\"\n        or r[\"_field\"] == \"req_headers\"\n        or r[\"_field\"] == \"res_timestamp\"\n        or r[\"_field\"] == \"res_status_code\"\n        or r[\"_field\"] == \"res_body\"\n        or r[\"_field\"] == \"res_duration_ms\"\n        or r[\"_field\"] == \"res_headers\"\n        ) \n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \n  |> filter(fn: (r) => r.req_timestamp == \"$detailsQuery\")\n  |> limit(n: 1)\n\ndata\n  |> map(fn: (r) => ({\n      Order: 1,\n      Field: \"Timestamp\",\n      Value: string(v: r.req_timestamp)\n  }))\n  |> yield(name: \"1_timestamp\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 2,\n      Field: \"API\",\n      Value: string(v: r.req_api)\n  }))\n  |> yield(name: \"2_api\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 3,\n      Field: \"Path\",\n      Value: string(v: r.req_path)\n  }))\n  |> yield(name: \"3_path\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 4,\n      Field: \"Method\",\n      Value: string(v: r.req_method)\n  }))\n  |> yield(name: \"4_method\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 5,\n      Field: \"Controller\",\n      Value: string(v: r.req_route_controller)\n  }))\n  |> yield(name: \"5_controller\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 6,\n      Field: \"Action\",\n      Value: string(v: r.req_route_action)\n  }))\n  |> yield(name: \"6_action\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 7,\n      Field: \"Query String\",\n      Value: string(v: r.req_query_string)\n  }))\n  |> yield(name: \"7_query_string\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 8,\n      Field: \"Body\",\n      Value: string(v: r.req_body)\n  }))\n  |> yield(name: \"8_body\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 9,\n      Field: \"Request Host\",\n      Value: string(v: r.req_host)\n  }))\n  |> yield(name: \"9_req_host\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 10,\n      Field: \"Request IP\",\n      Value: string(v: r.req_client_ip)\n  }))\n  |> yield(name: \"10_req_ip\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 11,\n      Field: \"Request Location\",\n      Value: string(v: r.req_location)\n  }))\n  |> yield(name: \"11_req_location\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 12,\n      Field: \"Request Headers\",\n      Value: string(v: r.req_headers)\n  }))\n  |> yield(name: \"12_req_headers\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 13,\n      Field: \"Response Timestamp\",\n      Value: string(v: r.res_timestamp)\n  }))\n  |> yield(name: \"13_res_timestamp\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 14,\n      Field: \"Response Code\",\n      Value: string(v: r.res_status_code)\n  }))\n  |> yield(name: \"14_res_status_code\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 15,\n      Field: \"Response Body\",\n      Value: string(v: r.res_body)\n  }))\n  |> yield(name: \"15_res_body\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 16,\n      Field: \"Response Time (ms)\",\n      Value: string(v: r.res_duration_ms)\n  }))\n  |> yield(name: \"16_res_duration_ms\")\n\ndata\n  |> map(fn: (r) => ({\n      Order: 17,\n      Field: \"Response Headers\",\n      Value: string(v: r.res_headers)\n  }))\n  |> yield(name: \"17_res_headers\")"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "table",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "query": "SELECT \n    time,\n    req_timestamp AS \"Hiden Timestamp\", \n    req_timestamp AS \"Show details\", \n    req_api AS \"API\",\n    req_path AS \"Path\",\n    req_method AS \"Method\",\n    res_status_code AS \"Code\",\n    res_body AS \"Response Body\"\nFROM /^(?:$dataTable)$/\nWHERE $timeFilter AND\n    res_status_code >= 400\n    AND req_api =~ /^($api)$/\nORDER BY \n    time DESC\n"
      }
     ]
    },
    {
     "title": "Response Times",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "iox",
       "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${dataTable:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"res_duration_ms\")\n  |> filter(fn: (r) => contains(value: r.req_api, set: ${api:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"req_path\", \"req_method\"])\n  |> map(fn: (r) => ({\n       r with \n       _value: r._value,\n       combined: r.req_path + \" - \" + r.req_method\n     }))\n  |> drop(columns: [\"req_path\", \"req_method\"])\n  |> rename(columns: {_value: \"Response Time (ms)\", combined: \"_value\"})\n  |> sort(columns: [\"_time\"], desc: true)\n",
       "rawSql": "SELECT\r\n  CONCAT(req_path, ' ', req_method) AS \"Path + Method\",\r\n  res_duration_ms AS \"Response Time (ms)\"\r\nFROM \"$dataTable\"\r\nWHERE $__timeFilter(time) AND \"req_api\" IN (${api:singlequote})\r\nORDER BY time DESC\r\nLIMIT 15"
      }
     ]
    },
    {
     "title": "Geomap",
     "type": "geomap",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 38 },
     "targets": [
      {
       "query": "SELECT \n    req_location AS \"Name\",\n    req_latitude AS \"Latitude\",\n    req_longitude AS \"Longitude\"\nFROM /^(?:$dataTable)$/\nWHERE $timeFilter AND req_api =~ /${api:regex}/\nGROUP BY req_location, req_latitude, req_longitude\n"
      }
     ]
    },
    {
     "title": "Connexions",
     "type": "table",
     "gridPos": { "h": 12, "w": 14, "x": 10, "y": 38 },
     "targets": [
      {
       "query": "SELECT\ntime,\nreq_host AS \"Host\",\nreq_client_ip AS \"Client IP\",\nreq_location AS \"Location\",\nreq_api AS \"API\"\nFROM /^(?:$dataTable)$/\nWHERE $timeFilter AND req_api =~ /^($api)$/\nORDER BY\ntime DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "📊 API Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2928 },
     "options": {
      "content": "<div style=\"text-align: left; width: 100%;\">\r\n    <hr style=\"border: 1px solid white; margin-top: 5px; margin-bottom: 10px;\">\r\n    <h2 style=\"font-weight: bold; font-size: 1.8em; margin-top: 0; margin-bottom: 5px;\">API Statistics</h2>\r\n</div>\r\n"
     }
    },
    {
     "title": "Use of APIs",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 2930 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement =~ /${dataTable:regex}/)\r\n  |> filter(fn: (r) => r._field == \"req_timestamp\")\r\n  |> filter(fn: (r) => exists r.req_api)\r\n  |> filter(fn: (r) => contains(value: r.req_api, set: ${api:json}))\r\n  |> group(columns: [\"req_api\"])\r\n  |> distinct(column: \"_value\")\r\n  |> count()\r\n  |> rename(columns: {_value: \"Count\", req_api: \"API\"})\r\n  |> map(fn: (r) => ({r with label: string(v: r.API) }))\r\n"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 17, "x": 7, "y": 2930 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${dataTable:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"req_timestamp\")\n  |> filter(fn: (r) => contains(value: r.req_api, set: ${api:json}))\n  |> group(columns: [\"req_api\"])\n  |> window(every: 1d)\n  |> count()\n  |> group(columns: [\"req_api\", \"_start\"])\n  |> pivot(rowKey: [\"_start\"], columnKey: [\"req_api\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with time: r._start }))\n  |> yield(name: \"count_by_api_per_day\")\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 2942 },
     "options": {
      "content": "<div style=\"text-align: left; width: 100%;\">\n    <hr style=\"border: 1px solid white; margin-top: 5px; margin-bottom: 10px;\">\n    <h2 style=\"font-weight: bold; font-size: 1.8em; margin-top: 0; margin-bottom: 5px;\">Average Response Times</h2>\n</div>\n"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 7, "x": 10, "y": 2942 },
     "options": {
      "content": "<div style=\"text-align: left; width: 100%;\">\n    <hr style=\"border: 1px solid white; margin-top: 5px; margin-bottom: 10px;\">\n    <h2 style=\"font-weight: bold; font-size: 1.8em; margin-top: 0; margin-bottom: 5px;\">Path + Method Count</h2>\n</div>\n"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 2942 },
     "options": {
      "content": "<div style=\"text-align: left; width: 100%;\">\n    <hr style=\"border: 1px solid white; margin-top: 5px; margin-bottom: 10px;\">\n    <h2 style=\"font-weight: bold; font-size: 1.8em; margin-top: 0; margin-bottom: 5px;\">Controller + Action Count</h2>\n</div>\n"
     }
    },
    {
     "title": "🌐 $api",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 10, "x": 0, "y": 2944 },
     "repeat": "api",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "iox",
       "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${dataTable:regex}/)\n  |> filter(fn: (r) => r[\"req_api\"] == \"$api\")\n  |> filter(fn: (r) => r[\"_field\"] == \"res_duration_ms\")\n  |> group(columns: [\"req_path\", \"req_method\"])\n  |> mean(column: \"_value\")\n  |> map(fn: (r) => ({ r with title: r[\"req_path\"] + \" - \" + r[\"req_method\"] }))\n  |> sort(columns: [\"_value\"], desc: true)\n",
       "rawSql": "SELECT\r\n  req_path AS \"Path\",\r\n  req_method AS \"Method\",\r\n  AVG(res_duration_ms) AS \"Avg Duration (ms)\"\r\nFROM \"$dataTable\"\r\nWHERE $__timeFilter(time) AND req_api = '$api'\r\nGROUP BY req_path, req_method\r\nORDER BY \"Avg Duration (ms)\" DESC"
      }
     ]
    },
    {
     "title": "🌐 $api",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 7, "x": 10, "y": 2944 },
     "repeat": "api",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement =~ /${dataTable:regex}/)\r\n  |> filter(fn: (r) => r.req_api == \"$api\")\r\n  |> group(columns: [\"req_path\", \"req_method\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({\r\n       Count: r._value / 14,\r\n       title: r.req_path  + \" - \" + r.req_method\r\n     }))\r\n  |> group()\r\n  |> sort(columns: [\"Count\"], desc: true)"
      }
     ]
    },
    {
     "title": "🌐 $api",
     "type": "bargauge",
     "description": "\n",
     "gridPos": { "h": 18, "w": 7, "x": 17, "y": 2944 },
     "repeat": "api",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement =~ /${dataTable:regex}/)\r\n  |> filter(fn: (r) => r.req_api == \"$api\")\r\n  |> group(columns: [\"req_route_controller\", \"req_route_action\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({\r\n       Count: r._value / 14,\r\n       title: r.req_route_controller  + \" - \" + r.req_route_action\r\n     }))\r\n  |> group()\r\n  |> sort(columns: [\"Count\"], desc: true)"
      }
     ]
    }
   ]
  },
  {
   "title": "🚩 Checkpoint Logger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
     "options": {
      "content": "<div style=\"text-align: left; width: 100%;\">\r\n    <hr style=\"border: 1px solid white; margin-top: 5px; margin-bottom: 10px;\">\r\n    <h2 style=\"font-weight: bold; font-size: 1.8em; margin-top: 0; margin-bottom: 5px;\">Checkpoint Logger</h2>\r\n</div>\r\n"
     }
    },
    {
     "title": "Checkpoints",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "query": "SELECT\n    time,\n    ckpt_api AS \"API\",\n    ckpt_message AS \"Message\", \n    ckpt_data AS \"Data\",\n    ckpt_path AS \"Path\", \n    ckpt_method AS \"Method\", \n    ckpt_controller AS \"Controller\", \n    ckpt_action AS \"Action\",\n    ckpt_ip AS \"IP\"\nFROM /^(?:$ckptDataTable)$/\nWHERE $timeFilter AND ckpt_api =~ /^($api)$/\nORDER BY time DESC\n"
      }
     ]
    },
    {
     "title": "Use of Checkpoints",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement =~ /${ckptDataTable:regex}/)\r\n  |> filter(fn: (r) => r._field == \"ckpt_timestamp\")\r\n  |> filter(fn: (r) => exists r.ckpt_api)\r\n  |> group(columns: [\"ckpt_api\"])\r\n  |> distinct(column: \"_value\")\r\n  |> count()\r\n  |> rename(columns: {_value: \"Count\", ckpt_api: \"API\"})\r\n  |> map(fn: (r) => ({ r with label: string(v: r.API) }))\r\n"
      }
     ]
    },
    {
     "title": "Checkpoint Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 17, "x": 7, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement =~ /${ckptDataTable:regex}/)\r\n  |> filter(fn: (r) => r._field == \"ckpt_timestamp\")\r\n  |> filter(fn: (r) => contains(value: r.ckpt_api, set: ${api:json}))\r\n  |> group(columns: [\"ckpt_api\"])\r\n  |> window(every: 1h)\r\n  |> count()\r\n  |> group(columns: [\"ckpt_api\", \"_start\"])\r\n  |> pivot(rowKey: [\"_start\"], columnKey: [\"ckpt_api\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with time: r._start }))\r\n  |> yield(name: \"heatmap_data\")\r\n"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<div style=\"\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n    border-top: 2px solid rgba(155, 104, 167, 0.3);\n    padding: 20px 30px;\n    font-family: Arial, sans-serif;\n    color: #9B68A7;\n    max-width: 100%;\n    margin: 25px auto 0;\n    font-size: 1em;\n\">\n    <div style=\"flex-grow: 1;\">\n        <p style=\"margin: 0; font-size: 1.1em;\">Watchdog Middleware: Vigilant API Monitoring</p>\n        <p style=\"margin: 8px 0 0; font-size: 1em; color: #7A4A7C;\">\n            ⚾️🐕\n        </p>\n    </div>\n    <div style=\"\n        display: flex;\n        flex-direction: column;\n        align-items: flex-end;\n    \">\n        <a href=\"https://github.com/RubenMartinezSiso/WatchdogMiddleware\" \n           target=\"_blank\" \n           style=\"text-decoration: none; color: #9B68A7; font-weight: bold; font-size: 1.1em;\">\n            📚 Explore the Repo\n        </a>\n        <p style=\"margin: 8px 0 0; font-size: 0.9em; color: #7A4A7C;\">\n            © 2025 Watchdog Middleware | v1.4.0\n        </p>\n    </div>\n</div>\n"
   }
  }
 ]
}