apiVersion: 1

datasources:
  - name: flux
    type: influxdb
    uid: influx_flux_uid
    access: proxy
    url: http://${DOCKER_INFLUXDB_INIT_HOST}:${DOCKER_INFLUXDB_INIT_PORT}
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

  - name: influxQL
    type: influxdb
    uid: influx_ql_uid
    access: proxy
    url: http://${DOCKER_INFLUXDB_INIT_HOST}:${DOCKER_INFLUXDB_INIT_PORT}
    database: ${DOCKER_INFLUXDB_INIT_BUCKET}
    user: ${DOCKER_INFLUXDB_INIT_USERNAME}
    secureJsonData:
      password: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    jsonData:
      httpMode: GET
      version: InfluxQL
